In [1]:
import pandas as pd

In [2]:
import matplotlib as plt

In [3]:
df = pd.read_csv("car-sales.csv")

In [4]:
df

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [5]:
pd.crosstab(df.Make, df.Doors)

Doors   3  4  5
Make           
BMW     0  0  1
Honda   0  3  0
Nissan  0  2  0
Toyota  1  3  0

In [6]:
car_sales = df[["Make", "Odometer (KM)"]]

In [7]:
car_sales

Make  Odometer (KM)
0  Toyota         150043
1   Honda          87899
2  Toyota          32549
3     BMW          11179
4  Nissan         213095
5  Toyota          99213
6   Honda          45698
7   Honda          54738
8  Toyota          60000
9  Nissan          31600

In [8]:
car_sales.groupby("Make").mean()

Odometer (KM)
Make                 
BMW      11179.000000
Honda    62778.333333
Nissan  122347.500000
Toyota   85451.250000

In [9]:
df["Price"] = df["Price"].str.replace('[\$\,]|\.\d*', '', regex=True).astype(int)

In [10]:
df

Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [11]:
cars_missing_drop = df.dropna()

In [12]:
cars_missing_drop

Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [13]:
df

Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [14]:
series_doors = pd.Series([5,5,5,5,5])

In [15]:
df["Seats"] = series_doors

In [16]:
df

Make Colour  Odometer (KM)  Doors  Price  Seats
0  Toyota  White         150043      4   4000    5.0
1   Honda    Red          87899      4   5000    5.0
2  Toyota   Blue          32549      3   7000    5.0
3     BMW  Black          11179      5  22000    5.0
4  Nissan  White         213095      4   3500    5.0
5  Toyota  Green          99213      4   4500    NaN
6   Honda   Blue          45698      4   7500    NaN
7   Honda   Blue          54738      4   7000    NaN
8  Toyota  White          60000      4   6250    NaN
9  Nissan  White          31600      4   9700    NaN

In [17]:
df.fillna(5, inplace = True)

In [18]:
df

Make Colour  Odometer (KM)  Doors  Price  Seats
0  Toyota  White         150043      4   4000    5.0
1   Honda    Red          87899      4   5000    5.0
2  Toyota   Blue          32549      3   7000    5.0
3     BMW  Black          11179      5  22000    5.0
4  Nissan  White         213095      4   3500    5.0
5  Toyota  Green          99213      4   4500    5.0
6   Honda   Blue          45698      4   7500    5.0
7   Honda   Blue          54738      4   7000    5.0
8  Toyota  White          60000      4   6250    5.0
9  Nissan  White          31600      4   9700    5.0

In [19]:
fuel_used = [3.4, 5.8, 7.9, 4.9, 8.2, 5.4, 5.8, 9.4, 7.5, 3.23]
df["Fuel used per 100 (Km)"] = fuel_used

In [20]:
df

Make Colour  Odometer (KM)  Doors  Price  Seats  Fuel used per 100 (Km)
0  Toyota  White         150043      4   4000    5.0                    3.40
1   Honda    Red          87899      4   5000    5.0                    5.80
2  Toyota   Blue          32549      3   7000    5.0                    7.90
3     BMW  Black          11179      5  22000    5.0                    4.90
4  Nissan  White         213095      4   3500    5.0                    8.20
5  Toyota  Green          99213      4   4500    5.0                    5.40
6   Honda   Blue          45698      4   7500    5.0                    5.80
7   Honda   Blue          54738      4   7000    5.0                    9.40
8  Toyota  White          60000      4   6250    5.0                    7.50
9  Nissan  White          31600      4   9700    5.0                    3.23

In [21]:
df["Total Fuel Used"] = df["Odometer (KM)"] / 100 * df["Fuel used per 100 (Km)"]

In [22]:
df

Make Colour  Odometer (KM)  Doors  Price  Seats  Fuel used per 100 (Km)  \
0  Toyota  White         150043      4   4000    5.0                    3.40   
1   Honda    Red          87899      4   5000    5.0                    5.80   
2  Toyota   Blue          32549      3   7000    5.0                    7.90   
3     BMW  Black          11179      5  22000    5.0                    4.90   
4  Nissan  White         213095      4   3500    5.0                    8.20   
5  Toyota  Green          99213      4   4500    5.0                    5.40   
6   Honda   Blue          45698      4   7500    5.0                    5.80   
7   Honda   Blue          54738      4   7000    5.0                    9.40   
8  Toyota  White          60000      4   6250    5.0                    7.50   
9  Nissan  White          31600      4   9700    5.0                    3.23   

   Total Fuel Used  
0         5101.462  
1         5098.142  
2         2571.371  
3          547.771  
4        17473.790  
5         5357.502  
6         2650.484  
7         5145.372  
8         4500.000  
9         1020.680

In [23]:
df["Wheels"] = 4

In [24]:
df

Make Colour  Odometer (KM)  Doors  Price  Seats  Fuel used per 100 (Km)  \
0  Toyota  White         150043      4   4000    5.0                    3.40   
1   Honda    Red          87899      4   5000    5.0                    5.80   
2  Toyota   Blue          32549      3   7000    5.0                    7.90   
3     BMW  Black          11179      5  22000    5.0                    4.90   
4  Nissan  White         213095      4   3500    5.0                    8.20   
5  Toyota  Green          99213      4   4500    5.0                    5.40   
6   Honda   Blue          45698      4   7500    5.0                    5.80   
7   Honda   Blue          54738      4   7000    5.0                    9.40   
8  Toyota  White          60000      4   6250    5.0                    7.50   
9  Nissan  White          31600      4   9700    5.0                    3.23   

   Total Fuel Used  Wheels  
0         5101.462       4  
1         5098.142       4  
2         2571.371       4  
3          547.771       4  
4        17473.790       4  
5         5357.502       4  
6         2650.484       4  
7         5145.372       4  
8         4500.000       4  
9         1020.680       4

In [25]:
df = df.drop("Total Fuel Used", axis = 1)

In [26]:
df

Make Colour  Odometer (KM)  Doors  Price  Seats  Fuel used per 100 (Km)  \
0  Toyota  White         150043      4   4000    5.0                    3.40   
1   Honda    Red          87899      4   5000    5.0                    5.80   
2  Toyota   Blue          32549      3   7000    5.0                    7.90   
3     BMW  Black          11179      5  22000    5.0                    4.90   
4  Nissan  White         213095      4   3500    5.0                    8.20   
5  Toyota  Green          99213      4   4500    5.0                    5.40   
6   Honda   Blue          45698      4   7500    5.0                    5.80   
7   Honda   Blue          54738      4   7000    5.0                    9.40   
8  Toyota  White          60000      4   6250    5.0                    7.50   
9  Nissan  White          31600      4   9700    5.0                    3.23   

   Wheels  
0       4  
1       4  
2       4  
3       4  
4       4  
5       4  
6       4  
7       4  
8       4  
9       4

In [27]:
df["Odometer (KM)"] = df["Odometer (KM)"].apply(lambda x : x /1.6)

In [28]:
df 

Make Colour  Odometer (KM)  Doors  Price  Seats  Fuel used per 100 (Km)  \
0  Toyota  White      93776.875      4   4000    5.0                    3.40   
1   Honda    Red      54936.875      4   5000    5.0                    5.80   
2  Toyota   Blue      20343.125      3   7000    5.0                    7.90   
3     BMW  Black       6986.875      5  22000    5.0                    4.90   
4  Nissan  White     133184.375      4   3500    5.0                    8.20   
5  Toyota  Green      62008.125      4   4500    5.0                    5.40   
6   Honda   Blue      28561.250      4   7500    5.0                    5.80   
7   Honda   Blue      34211.250      4   7000    5.0                    9.40   
8  Toyota  White      37500.000      4   6250    5.0                    7.50   
9  Nissan  White      19750.000      4   9700    5.0                    3.23   

   Wheels  
0       4  
1       4  
2       4  
3       4  
4       4  
5       4  
6       4  
7       4  
8       4  
9       4

In [29]:
df.rename(columns = {'Odometer (KM)':'Odometer (Mile)'}, inplace = True)


In [30]:
df

Make Colour  Odometer (Mile)  Doors  Price  Seats  \
0  Toyota  White        93776.875      4   4000    5.0   
1   Honda    Red        54936.875      4   5000    5.0   
2  Toyota   Blue        20343.125      3   7000    5.0   
3     BMW  Black         6986.875      5  22000    5.0   
4  Nissan  White       133184.375      4   3500    5.0   
5  Toyota  Green        62008.125      4   4500    5.0   
6   Honda   Blue        28561.250      4   7500    5.0   
7   Honda   Blue        34211.250      4   7000    5.0   
8  Toyota  White        37500.000      4   6250    5.0   
9  Nissan  White        19750.000      4   9700    5.0   

   Fuel used per 100 (Km)  Wheels  
0                    3.40       4  
1                    5.80       4  
2                    7.90       4  
3                    4.90       4  
4                    8.20       4  
5                    5.40       4  
6                    5.80       4  
7                    9.40       4  
8                    7.50       4  
9                    3.23       4

# Numpy Play around

In [31]:
import numpy as np


In [32]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [33]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

In [34]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [35]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [36]:
c[1][1][2]

6.0

In [37]:
a4 =  np.random.randint(10 , size= (2,3,4,5))

In [38]:
a4

array([[[[0, 8, 2, 7, 3],
         [9, 8, 7, 1, 5],
         [1, 9, 1, 9, 5],
         [2, 4, 5, 8, 6]],

        [[6, 2, 5, 4, 8],
         [4, 8, 2, 4, 9],
         [3, 2, 5, 2, 9],
         [4, 6, 1, 2, 6]],

        [[6, 8, 1, 1, 3],
         [7, 3, 8, 8, 7],
         [7, 4, 0, 8, 2],
         [7, 0, 6, 2, 3]]],


       [[[3, 4, 5, 6, 1],
         [9, 5, 9, 3, 6],
         [6, 7, 3, 5, 8],
         [5, 9, 5, 8, 8]],

        [[7, 2, 3, 2, 9],
         [8, 2, 1, 5, 7],
         [8, 0, 0, 3, 6],
         [1, 6, 8, 1, 8]],

        [[0, 7, 3, 7, 8],
         [0, 0, 3, 8, 9],
         [7, 7, 8, 0, 5],
         [0, 9, 8, 9, 9]]]])

In [39]:
a4.shape

(2, 3, 4, 5)

In [40]:
a4[1][1][0]

array([7, 2, 3, 2, 9])

In [51]:
b.shape

(2, 3)

In [43]:
a

array([1, 2, 3])

In [44]:
a_multiply_b = a *b 

In [45]:
a_multiply_b


array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [48]:
a_3_2 =  np.random.randint(10 , size= (3,2))
a_3_2

array([[5, 2],
       [1, 3],
       [0, 3]])

In [54]:
# Define a matrix with 2 rows and 3 columns
matrix_a = np.array([[1, 2, 3],
                    [4, 5, 6]])

# Define a matrix with 3 rows and 2 columns
matrix_b = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

# Perform matrix multiplication
result_matrix = np.dot(matrix_a, matrix_b)

# Alternatively, you can use the @ operator for matrix multiplication in Python 3.5 and above
# result_matrix = matrix_a @ matrix_b

print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)
print("\nResult of Matrix Multiplication:")
print(result_matrix)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of Matrix Multiplication:
[[ 58  64]
 [139 154]]


In [57]:
a_3_4 =  np.random.randint(10 , size= (3,4))
a_3_4

array([[0, 6, 5, 5],
       [8, 6, 7, 4],
       [6, 4, 8, 1]])

In [58]:
a_2_2 =  np.random.randint(10 , size= (2,2))
a_2_2

array([[5, 5],
       [5, 1]])

In [59]:
result = np.dot(a_3_4, a_2_2)


ValueError: shapes (3,4) and (2,2) not aligned: 4 (dim 1) != 2 (dim 0)

In [61]:
a_3_4.ndim

2

In [62]:
a_2_2.ndim

2

In [63]:
a_3_4.dot(a_2_2)

ValueError: shapes (3,4) and (2,2) not aligned: 4 (dim 1) != 2 (dim 0)

In [64]:
a_3_4

array([[0, 6, 5, 5],
       [8, 6, 7, 4],
       [6, 4, 8, 1]])

In [65]:
a_2_2

array([[5, 5],
       [5, 1]])