# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
array1 = np.array([1,2,3,4])

# Create a 2-dimensional NumPy array using np.array()
array2 = np.random.randint(10, size=(2,3))


# Create a 3-dimensional Numpy array using np.array()
array3 = np.random.randint(10, size = (2,3,3))

print(array1)

print(array2)
print(array3)


[1 2 3 4]
[[3 3 5]
 [9 4 4]]
[[[6 5 2]
  [0 8 0]
  [7 7 9]]

 [[4 6 9]
  [2 5 4]
  [1 7 6]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
array2.base


In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array1.shape
array1.size
array1.dtype


dtype('int32')

In [5]:
# Attributes of 2-dimensional array
array2.shape
#array2.size
#array2.dtype

(2, 3)

In [6]:
# Attributes of 3-dimensional array
array3.shape
array3.size
array3.dtype

dtype('int32')

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

In [8]:
# Create an array of shape (10, 2) with only ones
array2dOnly1 = np.ones(shape = (10,2))
array2dOnly1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
array3dOnly1 = np.ones(shape = (7,2,3))
array3dOnly1

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
array0to100 = np.arange(100)
array0to100

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_7_2 = np.random.randint(10, size = (7,2))
rand_7_2

array([[6, 3],
       [6, 3],
       [2, 6],
       [9, 3],
       [3, 1],
       [1, 8],
       [3, 0]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_7_2 = np.random.rand(3,5)
rand_7_2

array([[0.14999658, 0.61779718, 0.90088122, 0.55349068, 0.83598733],
       [0.87640664, 0.71922328, 0.20499563, 0.99455078, 0.4424458 ],
       [0.63774723, 0.96670039, 0.0828482 , 0.98173783, 0.7726486 ]])

In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_4_6 = np.random.rand(4,6)
rand_4_6

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [21]:
np.unique(a_var)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [ ]:
# Find the 0'th index of the latest array you created


In [ ]:
# Get the first 2 rows of latest array you created


In [ ]:
# Get the first 2 values of the first 2 rows of the latest array


In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables


In [ ]:
# Add the two arrays together


In [ ]:
# Create another array of ones of shape (5, 3)


In [ ]:
# Try add the array of ones and the other most recent array together


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)


In [ ]:
# Subtract the new array of ones from the other most recent array


In [ ]:
# Multiply the ones array with the latest array


In [ ]:
# Take the latest array to the power of 2 using '**'


In [ ]:
# Do the same thing with np.square()


In [ ]:
# Find the mean of the latest array using np.mean()


In [ ]:
# Find the maximum of the latest array using np.max()


In [ ]:
# Find the minimum of the latest array using np.min()


In [ ]:
# Find the standard deviation of the latest array


In [ ]:
# Find the variance of the latest array


In [ ]:
# Reshape the latest array to (3, 5, 1)


In [ ]:
# Transpose the latest array


What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [ ]:
# Perform a dot product on the two newest arrays you created


In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [ ]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [ ]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [ ]:
# Compare the two arrays with '>='


In [ ]:
# Find which elements of the first array are greater than 7


In [ ]:
# Which parts of each array are equal? (try using '==')


In [ ]:
# Sort one of the arrays you just created in ascending order


In [ ]:
# Sort the indexes of one of the arrays you just created


In [ ]:
# Find the index with the maximum value in one of the arrays you've created


In [ ]:
# Find the index with the minimum value in one of the arrays you've created


In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [ ]:
# Create an array of normally distributed random numbers


In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.